"""
Error Codes

Standard error codes for service operations.
Extracted from service_result_types to avoid import issues.
"""

from enum import Enum


class ErrorCode(Enum):
    """Standard error codes for service operations."""

    # General errors (1000-1999)
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    OPERATION_FAILED = "OPERATION_FAILED"

    # Database errors (2000-2999)
    DATABASE_ERROR = "DATABASE_ERROR"
    DATABASE_CONNECTION_ERROR = "DATABASE_CONNECTION_ERROR"
    DATABASE_QUERY_ERROR = "DATABASE_QUERY_ERROR"
    DATABASE_CONSTRAINT_ERROR = "DATABASE_CONSTRAINT_ERROR"
    RECORD_NOT_FOUND = "RECORD_NOT_FOUND"
    RECORD_ALREADY_EXISTS = "RECORD_ALREADY_EXISTS"
    RECORD_CONFLICT = "RECORD_CONFLICT"

    # Validation errors (3000-3999)
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INVALID_INPUT = "INVALID_INPUT"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    INVALID_FORMAT = "INVALID_FORMAT"
    INVALID_VALUE = "INVALID_VALUE"
    CONSTRAINT_VIOLATION = "CONSTRAINT_VIOLATION"

    # Permission errors (4000-4999)
    PERMISSION_DENIED = "PERMISSION_DENIED"
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
    RESOURCE_FORBIDDEN = "RESOURCE_FORBIDDEN"

    # Resource errors (5000-5999)
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS"
    RESOURCE_CONFLICT = "RESOURCE_CONFLICT"
    RESOURCE_LOCKED = "RESOURCE_LOCKED"
    RESOURCE_EXPIRED = "RESOURCE_EXPIRED"

    # Business logic errors (6000-6999)
    BUSINESS_LOGIC_ERROR = "BUSINESS_LOGIC_ERROR"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    OPERATION_NOT_ALLOWED = "OPERATION_NOT_ALLOWED"
    DEPENDENCY_ERROR = "DEPENDENCY_ERROR"
    CIRCULAR_DEPENDENCY = "CIRCULAR_DEPENDENCY"

    # Test execution errors (7000-7999)
    TEST_EXECUTION_ERROR = "TEST_EXECUTION_ERROR"
    TEST_TIMEOUT = "TEST_TIMEOUT"
    TEST_SETUP_FAILED = "TEST_SETUP_FAILED"
    TEST_CLEANUP_FAILED = "TEST_CLEANUP_FAILED"
    SCRIPT_VALIDATION_FAILED = "SCRIPT_VALIDATION_FAILED"
    SCRIPT_EXECUTION_FAILED = "SCRIPT_EXECUTION_FAILED"

    # Temporal errors (8000-8999)
    WORKFLOW_ERROR = "WORKFLOW_ERROR"
    ACTIVITY_ERROR = "ACTIVITY_ERROR"
    SCHEDULE_ERROR = "SCHEDULE_ERROR"
    WORKER_ERROR = "WORKER_ERROR"
