FROM node:20-alpine AS build

WORKDIR /app/frontend

COPY src/package*.json ./
RUN npm ci

COPY src/ ./
RUN npm run build

FROM nginx:alpine AS prod

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

